
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wegotogether
    username: root
    password: adfw4278
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
  data:
    redis:
      host: localhost
      port: 6379


jwt:
  secret:
    key: 0186a58ec5ee28e0f073d19fded854e58e9ab2410fd2e128e606345b902212f3



